language: python
python:
- '3.6'
cache:
  directories:
  - $HOME/.cache/pip
  - .arca/cache
install:
- python -m pip install --upgrade pip pipenv
- pipenv install --deploy --dev
before_script:  # encrypted variables aren't accessible in PRs
- 'if [ -n "$DOCKER_HUB_PASSWORD" ]; then docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"; fi'
- 'if [ -z "$DOCKER_HUB_PASSWORD" ]; then export ARCA_BACKEND_REGISTRY_PULL_ONLY=true; fi'
script:
- export NAUCSE_MAIN_REPO_URL=https://github.com/$TRAVIS_REPO_SLUG
- export NAUCSE_MAIN_REPO_BRANCH=$TRAVIS_BRANCH
- pipenv graph
# we utilize our own timeout here to fail the build and store the cache
# Travis CI would kill the entire job in 50 minutes, so we exit this after 40, to leave 10 minutes for setup + cache upload
- timeout 2400 pipenv run naucse freeze --verbose
after_script:
- echo "Suplementary logs:"
- cat .arca/naucse.log
# so Travis CI stores the whole log in its build log (https://github.com/travis-ci/travis-ci/issues/6018)
- sleep 1
deploy:
  provider: script
  skip_cleanup: true
  script: pipenv run naucse deploy --push --no-freeze
  on:
    branch: master
    repo: pyvec/naucse.python.cz
env:
  global:
  - secure: pEZZeBdTSg0WUQYfwKZCiM+VMmNf2GyCCDa5Qcw2xGaNi5Z3rb3IYntY5ACKtDazgjzul+AqHra7iEx41yictXu4wYYt1nSY7g+ilBq/SlefiTi92ZRLH9elEChOa4A2njeuFIzwLBRr4Hdnn+21Vd/uxbC0wGhRC5c11ixBVC7Kn6zatT2TXUN+zF5a63NgUDrY/SPMV0jX3nozFHOxAQmZqlV1VL7O5ihct+mLYxB6MhS1NO/v30cMwyQm9nO0wBGJ1YH5/SKk9ThvFKH15d0xLVjZMfhJ/sgqpRnuRw4awH7SV7p2BoF7/07P8VWnCNvJ+wCipd1PqAk3COgqriWCBx80auaevIDxzky4CUk/efd3WYOA4MnzSAvcjbcQjojjsi64WWwVAcWuweTA8AEYMhVdqWlMbo8E3Oa0dZcyscBo+L26OdAdKNUqeNVQ84oIcPN/iUCitLB5GVOc0cIkn9wFer66jSuwK9bRfOTmV6NaRdLt78Edo+e1wXx0sdTVasL/rtIRTJAKKUtF8D/8RFfCNopOcceAyPr/Ay3JjVEFk2rTWeZls8E8os3TN6evVawx0t2xA0qXYb6IIrb0CFxv6sz/pU7vkuzS8g+pdQnfMmNtQ01sGGyedTT4YQRcgGKmWG+kolOXQlxJCGOndgz3VGN3DCppA5Ahbfo=
  - ARCA_BACKEND=arca.backend.DockerBackend
  - NAUCSE_TRUSTED_REPOS=*
  - DOCKER_HUB_USERNAME=naucse
  - secure: eg0Lj+IvZnNwf6rK7ZNsrhZs0V2ap9TylSOh3B+xthmwLBGB2fxtVQrjJEAimwoUEEzO6XAyGWuKa2RMtPUYx0758diEZCBT2Ct9aprhz2m9girLyUynAAfBumVv/0iMYqh9QShzfGLkF/f3Z/bkIheVhKV7jBCy5iHBLGzlSr2i4lZjFUE/lYNnQh+KCVx9HGKmSm4111x57ID+N73poe5mshWE6QYw4gSjjwdMW4SYcABwkARFHLNc1cuZYJKwXtMeN1MHlp2bjdJB2wUtoyb7b8QSoGYu87egVsAHby5+ccClecu9LC6DWgFvXs/pCBriqiHPk72TC0Zfx3pWpAhQcGZ85FqN4ZNL3q2hahodHbML38FjcbgQFNE9s1eT2q+y16R8Hy34HhvDCEx13+4xwjPHNkkjm/kQOzQ1cBwmiP52PgmsxOtNVu9sEOVmSUShf9oz15E0bpX8U+GG4cjJN15vGgfvg5lkpuVdRnoz+voi+9i3yDZ4XBD9E79LZxmHkZ5gEXdRWXnI6YmE9Ejq2csyLr4RPmicslLd24QWWSYmJ2MWzSaJmSFBiw2OZn880EqRlaVKSUS0kzvT5YYo6eb36cslSVK9QVBCAgzRuPH0GHKhnV5cPOQjgNEGISmLbTgMubxILNT077dcXL7cbB29YCN+zIyAoFH9gCs=
services:
- docker
