language: python
python:
- '3.5'
cache:
- pip
script:
- echo 'No linters, no tests...'
deploy:
  provider: script
  script: python site.py deploy
  on:
    branch: master
    repo: pyvec/naucse.python.cz
env:
  global:
    secure: Q0e514kdzfx8ISSUIINPS+GjBZlgyc/fIuooV9vBgHmTmMxis7KBxew/OHVYmyvpSwvtLBMjCYwpIRPxNSInJRfTVBeWXOY9a1wAs+lrd38D6pC1Xx/TfLa+lGyEeuA/Ow3/3cGwaOmOLTDCruRKIaKB2c02HrDG/MWSV+leJ++jlvdFdGDXhjiqIEXvmqjOo9okFTU+u/GVwfQiXCV4/NfWENa4oLd8stWxGBGpKVpNAjZAHO158MDT587zXO04W1g2RmuSWfbCyFgPQO9tWwFYDfafKcfjmUni9LGbEzrrAHNmyYsS+j4DsKp9qT+4J5iqO5JLxv7FHvXp3/e4197bEgRVz1oa8CPq298wRTzvpDaameULAg0aGYAxEp6651JiJdDDgXjx3hxTNd/0umvBlQ6n6eDCm3VPn3IVbGStPMVAwFrAT9rC3azOkTgxU4CXNGdI64N379nqtUZjSgqWdYXUG0NI04SqVNWv3etBsxDPc5QrFXJRFgaYi5BtESjnZSml2gNLD4C+JPyaybJlsgsbbx5C8MYPI6WGepD0PUwFp44XfY8UAXSRAUXAFtzQLCpfJeFBTj3WNwwB4p1KHnF4AhwB/SGaKSNv3R3YI7LNTHlS1AZcH0OiM6ajQGwylCujlijiydN1NRy4x8MA1glkoG4fX8vjQzLOIr4=
